
platform :ios, '15.0'

target 'YUTool_Example' do
  use_frameworks!
  
  pod 'Masonry', :modular_headers => true
  
  pod 'YUTool', :path => '../'

  target 'YUTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
